### PR TITLE
Implemented interactive tutorial functionality across Android App.

### PR DESCRIPTION
**Pull request by mehad123**
- Included user interaction required for some steps, before next step appeared
- Included user interaction required as needed for certain steps, before next step appeared.
- Included beginning pop-up when help icon is clicked to ask the user if they want to start the tutorial
- Included option for tutorial to start at the  InteractionPage.java as well

### CODE REVIEW

**Review by Fahim-zzz — COMMENTED** [review]
There seems to be issues when users do not follow the predicted path with the tutorial. Some bug fixing is necessary. For example, exiting the tutorial isn't doesn't allow me to restart the tutorial until no is pressed and then retried.

**Comment by mehad123** [comment]
That's not a bug, the pop-up message is pointing out for the user to conduct the step, and then the next step of the tutorial will continue on after that.

**Comment by Fahim-zzz** [comment]
> That's not a bug, the pop-up message is pointing out for the user to conduct the step, and then the next step of the tutorial will continue on after that.

My fault, I like the direction, although some edge case handling will need to be implemented later on. LGTM

**Review by Fahim-zzz — APPROVED** [review]
I like the direction, although some edge case handling will need to be implemented later on. LGTM

**Comment by mehad123** [comment]
> I like the direction, although some edge case handling will need to be implemented later on. LGTM

Sounds good, I'll keep that in mind.

**Pull request merged**
